### ISSUE TITLE
Rename index.html to base.html + improvements

### ISSUE THREAD

**Issue by meDracula** [meDracula/Pyshare#34]
# Rename and improvements
- [x] The index.html should represent home.html #4 need for waiting for issue to close

**Comment by rishvantsingh** [comment]
OKkh Ill do it.

**Comment by meDracula** [comment]
> OKkh Ill do it.

Hi rishvantsignh, love the enthusiasm but this is a school project in web frameworks and design from Teknikhögskolan. 
Thu I do truly appreciate your open source sprite. But i sorry to have to decline your help.
